/**
 * EntE
 * (c) 2017-present, Simon Knott <info@simonknott.de>
 *
 * This source code is licensed under the GNU Affero General Public License
 * found in the LICENSE file in the root directory of this source tree.
 */

export const CREATE_ENTRY_REQUEST = "CREATE_ENTRY_REQUEST";
export const CREATE_ENTRY_SUCCESS = "CREATE_ENTRY_SUCCESS";
export const CREATE_ENTRY_ERROR = "CREATE_ENTRY_ERROR";

export const CREATE_USERS_REQUEST = "CREATE_USERS_REQUEST";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR";

export const SIGN_ENTRY_REQUEST = "SIGN_ENTRY_REQUEST";
export const SIGN_ENTRY_SUCCESS = "SIGN_ENTRY_SUCCESS";
export const SIGN_ENTRY_ERROR = "SIGN_ENTRY_ERROR";

export const UNSIGN_ENTRY_REQUEST = "UNSIGN_ENTRY_REQUEST";
export const UNSIGN_ENTRY_SUCCESS = "UNSIGN_ENTRY_SUCCESS";
export const UNSIGN_ENTRY_ERROR = "UNSIGN_ENTRY_ERROR";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_ENTRY_REQUEST = "GET_ENTRY_REQUEST";
export const GET_ENTRY_SUCCESS = "GET_ENTRY_SUCCESS";
export const GET_ENTRY_ERROR = "GET_ENTRY_ERROR";

export const GET_ENTRIES_REQUEST = "GET_ENTRIES_REQUEST";
export const GET_ENTRIES_SUCCESS = "GET_ENTRIES_SUCCESS";
export const GET_ENTRIES_ERROR = "GET_ENTRIES_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const DOWNLOAD_EXCEL_EXPORT_REQUEST = "DOWNLOAD_EXCEL_EXPORT_REQUEST";
export const DOWNLOAD_EXCEL_EXPORT_SUCCESS = "DOWNLOAD_EXCEL_EXPORT_SUCCESS";
export const DOWNLOAD_EXCEL_EXPORT_ERROR = "DOWNLOAD_EXCEL_EXPORT_ERROR";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_SLOTS_REQUEST = "GET_SLOTS_REQUEST";
export const GET_SLOTS_SUCCESS = "GET_SLOTS_SUCCESS";
export const GET_SLOTS_ERROR = "GET_SLOTS_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const DELETE_ENTRY_REQUEST = "DELETE_ENTRY_REQUEST";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_ERROR = "DELETE_ENTRY_ERROR";

export const IMPORT_USERS_REQUEST = "IMPORT_USERS_REQUEST";
export const IMPORT_USERS_SUCCESS = "IMPORT_USERS_SUCCESS";
export const IMPORT_USERS_ERROR = "IMPORT_USERS_ERROR";

export const FETCH_INSTANCE_CONFIG_REQUEST = "FETCH_INSTANCE_CONFIG_REQUEST";
export const FETCH_INSTANCE_CONFIG_SUCCESS = "FETCH_INSTANCE_CONFIG_SUCCESS";
export const FETCH_INSTANCE_CONFIG_ERROR = "FETCH_INSTANCE_CONFIG_ERROR";

export const SET_LOGIN_BANNER_REQUEST = "SET_LOGIN_BANNER_REQUEST";
export const SET_LOGIN_BANNER_SUCCESS = "SET_LOGIN_BANNER_SUCCESS";
export const SET_LOGIN_BANNER_ERROR = "SET_LOGIN_BANNER_ERROR";

export const SET_DEFAULT_DEFAULT_LANGUAGE_REQUEST =
  "SET_DEFAULT_DEFAULT_LANGUAGE_REQUEST";
export const SET_DEFAULT_DEFAULT_LANGUAGE_SUCCESS =
  "SET_DEFAULT_DEFAULT_LANGUAGE_SUCCESS";
export const SET_DEFAULT_DEFAULT_LANGUAGE_ERROR =
  "SET_DEFAULT_DEFAULT_LANGUAGE_ERROR";

export const SET_PARENT_SIGNATURE_EXPIRY_TIME_REQUEST =
  "SET_PARENT_SIGNATURE_EXPIRY_TIME_REQUEST";
export const SET_PARENT_SIGNATURE_EXPIRY_TIME_SUCCESS =
  "SET_PARENT_SIGNATURE_EXPIRY_TIME_SUCCESS";
export const SET_PARENT_SIGNATURE_EXPIRY_TIME_ERROR =
  "SET_PARENT_SIGNATURE_EXPIRY_TIME_ERROR";

export const SET_PARENT_SIGNATURE_NOTIFICATION_TIME_REQUEST =
  "SET_PARENT_SIGNATURE_NOTIFICATION_TIME_REQUEST";
export const SET_PARENT_SIGNATURE_NOTIFICATION_TIME_SUCCESS =
  "SET_PARENT_SIGNATURE_NOTIFICATION_TIME_SUCCESS";
export const SET_PARENT_SIGNATURE_NOTIFICATION_TIME_ERROR =
  "SET_PARENT_SIGNATURE_NOTIFICATION_TIME_ERROR";

export const SET_ENTRY_CREATION_DAYS_REQUEST =
  "SET_ENTRY_CREATION_DAYS_REQUEST";
export const SET_ENTRY_CREATION_DAYS_SUCCESS =
  "SET_ENTRY_CREATION_DAYS_SUCCESS";
export const SET_ENTRY_CREATION_DAYS_ERROR = "SET_ENTRY_CREATION_DAYS_ERROR";

export const UPDATE_MANAGER_NOTES_REQUEST = "UPDATE_MANAGER_NOTES_REQUEST";
export const UPDATE_MANAGER_NOTES_SUCCESS = "UPDATE_MANAGER_NOTES_SUCCESS";
export const UPDATE_MANAGER_NOTES_ERROR = "UPDATE_MANAGER_NOTES_ERROR";

export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FILTER_SCOPE = "SET_FILTER_SCOPE";
export const SET_COLOR_SCHEME = "SET_COLOR_SCHEME";

export const LOGOUT = "LOGOUT";

export const ADD_REVIEWED_RECORD_REQUEST = "ADD_REVIEWED_RECORD_REQUEST";
export const ADD_REVIEWED_RECORD_SUCCESS = "ADD_REVIEWED_RECORD_SUCCESS";
export const ADD_REVIEWED_RECORD_ERROR = "ADD_REVIEWED_RECORD_ERROR";

export const PROMOTE_TEACHER_REQUEST = "PROMOTE_TEACHER_REQUEST";
export const PROMOTE_TEACHER_SUCCESS = "PROMOTE_TEACHER_SUCCESS";
export const PROMOTE_TEACHER_ERROR = "PROMOTE_TEACHER_ERROR";

export const DEMOTE_MANAGER_REQUEST = "DEMOTE_MANAGER_REQUEST";
export const DEMOTE_MANAGER_SUCCESS = "DEMOTE_MANAGER_SUCCESS";
export const DEMOTE_MANAGER_ERROR = "DEMOTE_MANAGER_ERROR";

const makeTriplet = (title: string) => [
  title + "_REQUEST",
  title + "_SUCCESS",
  title + "_ERROR"
];

export const [
  MANAGER_REACHED_OUT_REQUEST,
  MANAGER_REACHED_OUT_SUCCESS,
  MANAGER_REACHED_OUT_ERROR
] = makeTriplet("MANAGER_REACHED_OUT");
