variables:
  CONTAINER_BASE: registry.gitlab.com/skn0tt/ente
  CONTAINER_UI_TEST_IMAGE: $CONTAINER_BASE/ui:$CI_COMMIT_REF_NAME
  CONTAINER_UI_RELEASE_IMAGE: $CONTAINER_BASE/ui:latest
  CONTAINER_API_TEST_IMAGE: $CONTAINER_BASE/api:$CI_COMMIT_REF_NAME
  CONTAINER_API_RELEASE_IMAGE: $CONTAINER_BASE/api:latest
  CONTAINER_ROTATOR_TEST_IMAGE: $CONTAINER_BASE/rotator:$CI_COMMIT_REF_NAME
  CONTAINER_ROTATOR_RELEASE_IMAGE: $CONTAINER_BASE/rotator:latest
  CONTAINER_PROXY_TEST_IMAGE: $CONTAINER_BASE/nginx-proxy:$CI_COMMIT_REF_NAME
  CONTAINER_PROXY_RELEASE_IMAGE: $CONTAINER_BASE/nginx-proxy:latest

stages:
  - build
  - test
  - release

#
# Build
#
Build API:
  image: skn0tt/dind-make
  stage: build
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/api
    - make build IMAGE_TAG=$CONTAINER_API_TEST_IMAGE
    - docker push $CONTAINER_API_TEST_IMAGE

Build UI:
  image: skn0tt/dind-make
  stage: build
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/ui
    - make build IMAGE_TAG=$CONTAINER_UI_TEST_IMAGE
    - docker push $CONTAINER_UI_TEST_IMAGE

Build nginx-proxy:
  image: skn0tt/dind-make
  stage: build
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/nginx-proxy
    - make build IMAGE_TAG=$CONTAINER_PROXY_TEST_IMAGE
    - docker push $CONTAINER_PROXY_TEST_IMAGE

Build rotator:
  image: skn0tt/dind-make
  stage: build
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd packages/rotator
    - make build IMAGE_TAG=$CONTAINER_ROTATOR_TEST_IMAGE
    - docker push $CONTAINER_ROTATOR_TEST_IMAGE

#
# Test
#

# Test
.Compose Startup Test:
  image: docker
  stage: test
  only:
    - master
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - apk add --update py-pip
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

.Test API:
  image: node
  stage: test
  except:
    - master
  before_script:
    - cd packages/api
    - yarn
  script:
    - yarn test

Test UI:
  image: node
  stage: test
  except:
    - master
  before_script:
    - cd packages/ui
    - yarn
  script:
    - yarn test

# Linting
Lint API:
  image: node
  stage: test
  except:
    - master
  before_script:
    - cd packages/api
    - yarn
  script:
    - yarn lint

Lint UI:
  image: node
  stage: test
  except:
    - master
  before_script:
    - cd packages/ui
    - yarn
  script:
    - yarn lint

release:staging:
  stage: release
  image: williamyeh/ansible:debian9
  only:
    - master
  tags:
    - ansible
  environment:
    name: staging
    url: http://bull.simonknott.de
  script:
    - ansible-playbook -i staging.yml deploy-staging.yml
