include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  YARN_CACHE_FOLDER: .yarn-cache
  DAST_DISABLED: "true"
  TEST_DISABLED: "true"

.yarn_cache: &yarn_cache
  key: "test-yarn"
  paths:
    - node_modules/
    - .yarn-cache
    - .next/cache

test:e2e:
  stage: test
  image: circleci/node:12.16-browsers
  services:
    - mariadb:10.4
    - redis:4.0.10
    - mailhog/mailhog:v1.0.0
  variables:
    BASE_URL: localhost:3000
    REDIS_HOST: redis
    MYSQL_HOST: mariadb
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: ente
    MYSQL_USERNAME: root
    MYSQL_PASSWORD: root
    SMTP_HOST: mailhog-mailhog
    SMTP_PORT: 1025
  script:
    - yarn
    - yarn build
    - echo "dist_size $(du --human-readable --apparent-size --summarize .next | cut -f1)" > metrics.txt
    - yarn start > e2e.log &
    - curl localhost:3000/api/status # warm up server
    - yarn test:e2e:headless --app "echo i've already been started earlier"
  needs: []
  cache:
    <<: *yarn_cache
  interruptible: true
  only:
    - branches
    - tags
  artifacts:
    when: always
    paths:
      - screenshots/
      - e2e.log
    reports:
      junit: e2e.xml
      metrics: metrics.txt

test:unit:
  stage: test
  image: node:12.16
  script:
    - yarn
    - yarn test:tsc
    - yarn test:unit --ci --reporters=default --reporters=jest-junit --collect-coverage
  needs: []
  cache:
    <<: *yarn_cache
  interruptible: true
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  only:
    - branches
    - tags
  artifacts:
    when: always
    paths:
      - coverage/lcov-report/
      - junit.xml
    reports:
      junit: junit.xml

release:trigger_deployment:
  stage: .post
  trigger: skn0tt/EntE-deployments
  variables:
    NEW_VERSION: $CI_COMMIT_TAG
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
