stages:
  - test
  - build

Test API:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn test

Test UI:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn test

Lint API:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn lint

Lint UI:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn lint

Build API:
  image: docker:latest
  only:
    - master
  services:
    - docker:dind
  stage: build
  script:
    - cd api
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest

Build UI:
  image: docker:latest
  only:
    - master
  services:
    - docker:dind
  stage: build
  script:
    - cd ui
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest

Build Reverse Proxy:
  image: docker:latest
  only:
    - master
  services:
    - docker:dind
  stage: build
  script:
    - cd reverseproxy
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy:latest