stages:
  - build
  - test
  - upload

variables:
  CONTAINER_BASE: registry.gitlab.com/skn0tt/entschuldigungsverfahren
  CONTAINER_UI_TEST_IMAGE: $CONTAINER_BASE/ui:$CI_COMMIT_REF_NAME
  CONTAINER_UI_RELEASE_IMAGE: $CONTAINER_BASE/ui:latest
  CONTAINER_API_TEST_IMAGE: $CONTAINER_BASE/api:$CI_COMMIT_REF_NAME
  CONTAINER_API_RELEASE_IMAGE: $CONTAINER_BASE/api:latest
  CONTAINER_REVERSEPROXY_TEST_IMAGE: $CONTAINER_BASE/reverseproxy:$CI_COMMIT_REF_NAME
  CONTAINER_REVERSEPROXY_RELEASE_IMAGE: $CONTAINER_BASE/reverseproxy:latest

#
# Build
#
Build API:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd api
    - docker build --pull -t $CONTAINER_API_TEST_IMAGE .
    - docker push $CONTAINER_API_TEST_IMAGE

Build UI:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd ui
    - docker build --pull -t $CONTAINER_UI_TEST_IMAGE .
    - docker push $CONTAINER_UI_TEST_IMAGE

Build Reverse Proxy:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd reverseproxy
    - docker build --pull -t $CONTAINER_REVERSEPROXY_TEST_IMAGE .
    - docker push $CONTAINER_REVERSEPROXY_TEST_IMAGE

#
# Test
#

# Test
Compose Startup Test:
  image: docker
  stage: test
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - apk add --update py-pip
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

Test API:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

Test UI:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

# Linting
Lint API:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn lint

Lint UI:
  image: node
  stage: test
  before_script:
    - cd ui
    - yarn
  script:
    - yarn lint

Credentials:
  image: frolvlad/alpine-bash
  stage: test
  script:
    - cd ui/src/interfaces
    - "grep -nwc index.ts -e \"username: '',\" | grep -q 2"
    - "grep -nwc index.ts -e \"password: '',\" | grep -q 1"

#
# Upload
#
Push Images:
  image: docker
  stage: upload
  variables:
    GIT_STRATEGY: none
  only:
    - master
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - docker pull $CONTAINER_UI_TEST_IMAGE
    - docker pull $CONTAINER_API_TEST_IMAGE
    - docker pull $CONTAINER_REVERSEPROXY_TEST_IMAGE
    - docker tag $CONTAINER_UI_TEST_IMAGE $CONTAINER_UI_RELEASE_IMAGE
    - docker tag $CONTAINER_API_TEST_IMAGE $CONTAINER_API_RELEASE_IMAGE
    - docker tag $CONTAINER_REVERSEPROXY_TEST_IMAGE $CONTAINER_REVERSEPROXY_RELEASE_IMAGE
    - docker push $CONTAINER_UI_RELEASE_IMAGE
    - docker push $CONTAINER_API_RELEASE_IMAGE
    - docker push $CONTAINER_REVERSEPROXY_RELEASE_IMAGE
