variables:
  CONTAINER_BASE: registry.gitlab.com/skn0tt/entschuldigungsverfahren
  CONTAINER_UI_TEST_IMAGE: $CONTAINER_BASE/ui:$CI_COMMIT_REF_NAME
  CONTAINER_UI_RELEASE_IMAGE: $CONTAINER_BASE/ui:latest
  CONTAINER_API_TEST_IMAGE: $CONTAINER_BASE/api:$CI_COMMIT_REF_NAME
  CONTAINER_API_RELEASE_IMAGE: $CONTAINER_BASE/api:latest
  CONTAINER_REVERSEPROXY_TEST_IMAGE: $CONTAINER_BASE/reverseproxy:$CI_COMMIT_REF_NAME
  CONTAINER_REVERSEPROXY_RELEASE_IMAGE: $CONTAINER_BASE/reverseproxy:latest

stages:
  - build
  - test
  - release

#
# Build
#
Build API:
  image: docker
  stage: build
  only:
    - master
  when: manual
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd api
    - docker build -t $CONTAINER_API_TEST_IMAGE .
    - docker push $CONTAINER_API_TEST_IMAGE

Build UI:
  image: docker
  stage: build
  only:
    - master
  when: manual
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd ui
    - docker build -t $CONTAINER_UI_TEST_IMAGE .
    - docker push $CONTAINER_UI_TEST_IMAGE

Build Reverse Proxy:
  image: docker
  stage: build
  only:
    - master
  when: manual
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd reverseproxy
    - docker build -t $CONTAINER_REVERSEPROXY_TEST_IMAGE .
    - docker push $CONTAINER_REVERSEPROXY_TEST_IMAGE

#
# Test
#

# Test
Compose Startup Test:
  image: docker
  stage: test
  only:
    - master
  when: manual
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - apk add --update py-pip
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

Test API:
  image: node
  stage: test
  except:
    - master
  when: manual
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

Test UI:
  image: node
  stage: test
  except:
    - master
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

# Linting
Lint API:
  image: node
  stage: test
  except:
    - master
  when: manual
  before_script:
    - cd api
    - yarn
  script:
    - yarn lint

Lint UI:
  image: node
  stage: test
  except:
    - master
  when: manual
  before_script:
    - cd ui
    - yarn
  script:
    - yarn lint

Credentials:
  image: frolvlad/alpine-bash
  stage: test
  except:
    - master
  when: manual
  script:
    - cd ui/src/interfaces
    - "grep -nwc index.ts -e \"username: '',\" | grep -q 2"
    - "grep -nwc index.ts -e \"password: '',\" | grep -q 1"

release:staging:
  stage: release
  image: williamyeh/ansible:debian9
  only:
    - master
  tags:
    - ansible
  environment:
    name: staging
    url: http://bull.simonknott.de
  script:
    - ansible-playbook -i staging.yml ansible-deploy.yml
