stages:
  - test
  - build
  - test:e2e
  - generate
  - deploy
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

include:
  template: SAST.gitlab-ci.yml

sast:
  stage: test

test:unit:
  image: node:10
  stage: test
  script: "./scripts/ci/test_unit.sh"
  cache:
    key: "test-unit"
    paths:
      - node_modules/
  dependencies: []
  artifacts:
    paths:
      - coverage/lcov-report/
      - junit.xml

test:tsc:
  image: node:10
  stage: test
  script: "./scripts/ci/test_tsc.sh"
  cache:
    key: "test-unit"
    paths:
      - node_modules/
  dependencies: []

test:version:
  image:
    name: node:10
    entrypoint: [""]
  stage: test
  dependencies: []
  script: "./scripts/ci/test_version.sh"

license_management:
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/license-management:$CI_SERVER_VERSION_MAJOR-$CI_SERVER_VERSION_MINOR-stable"
    entrypoint: [""]
  stage: test
  allow_failure: true
  script:
    - /run.sh analyze .
  artifacts:
    paths: [gl-license-management-report.json]

build:api:
  image: skn0tt/dind-make
  stage: build
  dependencies: []
  services:
    - docker:19.03.0-dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script: "./scripts/ci/build_docker.sh api"

build:ui:
  image: skn0tt/dind-make
  stage: build
  dependencies: []
  services:
    - docker:19.03.0-dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script: "./scripts/ci/build_docker.sh ui"

build:docker-app:
  image: docker:stable
  stage: build
  dependencies: []
  services:
    - docker:19.03.0-dind
  script: "./scripts/ci/build_dockerapp.sh"

test:e2e:
  image: skn0tt/node-browsers-docker-app:node-10-docker-app-v0.6.0
  stage: test:e2e
  dependencies: []
  cache:
    key: "test-e2e"
    paths:
      - node_modules/
  services:
    - name: docker:stable-dind
      alias: dind
  variables:
    BASE_URL: "http://dind:80"
    DOCKER_HOST: dind:2375
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script: ./scripts/ci/test_e2e.sh
  artifacts:
    when: always
    paths:
      - screenshots/
      - e2e.xml
      - tests/e2e/logs.txt

generate:docs:
  image: python
  stage: generate
  dependencies: []
  cache:
    key: "generate-docs"
    paths:
      - .cache/pip
      - venv/
  script: "./scripts/ci/generate_docs.sh"
  artifacts:
    paths:
      - docs_dist/

generate:allure:
  image: skn0tt/allure
  stage: generate
  dependencies:
    - test:unit
    - test:e2e
  script: "./scripts/ci/generate_allure.sh"
  artifacts:
    paths:
      - allure-report/

generate:pages:
  image: node:10
  stage: generate
  dependencies: []
  script: "./scripts/ci/generate_pages.sh"
  artifacts:
    paths:
      - assets/pages/dist/

.now_deploy_template: &now_deploy_template
  image: node:10
  stage: deploy
  only:
    - master
  variables:
    NOW_SCOPE: "--scope ente"
    NOW_SECRET: "--token=$NOW_TOKEN"
  before_script:
    - yarn global add now

deploy:pages:
  <<: *now_deploy_template
  dependencies:
    - generate:pages
  script:
    # assets/pages/dist contains pages
    - NOW_DEPLOYMENT=$(now $NOW_SECRET $NOW_SCOPE --name product-website assets/pages/dist)
    - sleep 10
    - now $NOW_SECRET $NOW_SCOPE alias $NOW_DEPLOYMENT ente.app
    - now $NOW_SECRET $NOW_SCOPE alias $NOW_DEPLOYMENT www.ente.app

deploy:coverage:
  <<: *now_deploy_template
  dependencies:
    - test:unit
  script:
    # coverage/lcov-report contains line coverage report
    - NOW_DEPLOYMENT=$(now $NOW_SECRET $NOW_SCOPE --name coverage-report coverage/lcov-report/)
    - sleep 10
    - now $NOW_SECRET $NOW_SCOPE alias $NOW_DEPLOYMENT coverage-report.ente.app

deploy:test-report:
  <<: *now_deploy_template
  dependencies:
    - generate:allure
  script:
    # allure-report/ contains report files
    - NOW_DEPLOYMENT=$(now $NOW_SECRET $NOW_SCOPE --name test-report allure-report)
    - sleep 10
    - now $NOW_SECRET $NOW_SCOPE alias $NOW_DEPLOYMENT test-report.ente.app

deploy:docs:
  <<: *now_deploy_template
  dependencies:
    - generate:docs
  script:
    - NOW_DEPLOYMENT=$(now $NOW_SECRET $NOW_SCOPE --name docs docs_dist)
    - sleep 10
    - now $NOW_SECRET $NOW_SCOPE alias $NOW_DEPLOYMENT docs.ente.app

deploy:images:
  image: docker:stable
  stage: deploy
  dependencies: []
  services:
    - docker:19.03.0-dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script: "./scripts/ci/publish_images.sh"

release:trigger_deployment:
  image: tutum/curl
  stage: release
  dependencies: []
  variables:
    GIT_STRATEGY: none
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[NEW_VERSION]=$CI_COMMIT_TAG" --form ref=master https://gitlab.com/api/v4/projects/Skn0tt%2FEntE-deployments/trigger/pipeline
