stages:
  - build
  - test
  - upload

services:
  - docker:dind

variables:
  CONTAINER_UI_TEST_IMAGE: registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:$CI_COMMIT_REF_NAME
  CONTAINER_UI_RELEASE_IMAGE: registry.gitlab.com/my-group/my-project/ui:latest
  CONTAINER_API_TEST_IMAGE: registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:$CI_COMMIT_REF_NAME
  CONTAINER_API_RELEASE_IMAGE: registry.gitlab.com/my-group/my-project/api:latest
  CONTAINER_REVERSEPROXY_TEST_IMAGE: registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy:$CI_COMMIT_REF_NAME
  CONTAINER_REVERSEPROXY_RELEASE_IMAGE: registry.gitlab.com/my-group/my-project/reverseproxy:latest

#
# Build
#
Build API:
  image: docker
  stage: build
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd api
    - docker build --pull -t $CONTAINER_API_TEST_IMAGE .
    - docker push $CONTAINER_API_TEST_IMAGE

Build UI:
  image: docker
  stage: build
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd ui
    - docker build --pull -t $CONTAINER_UI_TEST_IMAGE .
    - docker push $CONTAINER_UI_TEST_IMAGE

Build Reverse Proxy:
  image: docker
  stage: build
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd reverseproxy
    - docker build --pull -t $CONTAINER_REVERSEPROXY_TEST_IMAGE .
    - docker push $CONTAINER_REVERSEPROXY_TEST_IMAGE

#
# Test
#

# Test
Compose Startup Test:
  image: docker
  stage: test
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - apk add --update py-pip
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

Test API:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

Test UI:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn test

# Linting
Lint API:
  image: node
  stage: test
  before_script:
    - cd api
    - yarn
  script:
    - yarn lint

Lint UI:
  image: node
  stage: test
  before_script:
    - cd ui
    - yarn
  script:
    - yarn lint

#
# Upload
#
Push Images:
  image: docker
  stage: upload
  only:
    - master
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - docker pull $CONTAINER_UI_TEST_IMAGE
    - docker pull $CONTAINER_API_TEST_IMAGE
    - docker pull $CONTAINER_REVERSEPROXY_TEST_IMAGE
    - docker tag $CONTAINER_UI_TEST_IMAGE $CONTAINER_UI_RELEASE_IMAGE
    - docker tag $CONTAINER_API_TEST_IMAGE $CONTAINER_API_RELEASE_IMAGE
    - docker tag $CONTAINER_REVERSEPROXY_TEST_IMAGE $CONTAINER_REVERSEPROXY_RELEASE_IMAGE
    - docker push $CONTAINER_UI_RELEASE_IMAGE
    - docker push $CONTAINER_API_RELEASE_IMAGE
    - docker push $CONTAINER_REVERSEPROXY_RELEASE_IMAGE
