include:
  - template: Auto-DevOps.gitlab-ci.yml

# Disable Auto-DevOps 'test' job
test:
  only:
    variables:
      - $UNSET_VARIABLE == "how am I set? i must not be set."

.yarn_cache: &yarn_cache
  key: "test-yarn"
  paths:
    - node_modules/
    - .yarn
    - .next/cache

test:e2e:
  stage: test
  image: circleci/node:12.16-browsers
  services:
    - mariadb:10.4
    - redis:4.0.10
    - mailhog/mailhog:v1.0.0
  variables:
    BASE_URL: localhost:3000
    REDIS_HOST: redis
    MYSQL_HOST: mariadb
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: ente
    MYSQL_USERNAME: root
    MYSQL_PASSWORD: root
    SMTP_HOST: mailhog
    SMTP_PORT: 1025
  script:
    - yarn
    - yarn build
    - echo "dist_size $(du --human-readable --apparent-size --summarize .next | cut -f1)" > metrics.txt
    - yarn test:e2e:headless --app "yarn start > e2e.log"
  needs: []
  cache:
    <<: *yarn_cache
  interruptible: true
  artifacts:
    when: always
    paths:
      - screenshots/
      - e2e.log
    reports:
      junit: e2e.xml
      metrics: metrics.txt

test:unit:
  stage: test
  image: node:12.16
  script:
    - yarn
    - yarn test:tsc
    - yarn test:unit --ci --reporters=default --reporters=jest-junit --collect-coverage
  needs: []
  cache:
    <<: *yarn_cache
  interruptible: true
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    paths:
      - coverage/lcov-report/
      - junit.xml
    reports:
      junit: junit.xml
