stages:
  - test
  - upload
  - build

services:
  - docker:dind

Build API:
  image: docker:latest
  stage: build
  script:
    - cd api
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest

Build UI:
  image: docker:latest
  stage: build
  script:
    - cd ui
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest

Build Reverse Proxy:
  image: docker:latest
  stage: build
  script:
    - cd reverseproxy
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy:latest

Compose Startup Test:
  image: docker:latest
  stage: test
  script:
    - wget -O wait-for "https://raw.githubusercontent.com/eficode/wait-for/master/wait-for"
    - chmod +x ./wait-for
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
    - ./wait-for localhost:80 --timeout=90

Test API:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn test

Test UI:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn test

Lint API:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn lint

Lint UI:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn lint
