stages:
  - test
  - build

test_api:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn test

test_ui:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn test

lint_api:
  image: node
  stage: test
  script:
    - cd api
    - yarn
    - yarn lint

lint_ui:
  image: node
  stage: test
  script:
    - cd ui
    - yarn
    - yarn lint

build_api:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - cd api
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest

build_ui:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - cd ui
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest .
    - docker push registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:latest
