- name: Update Compose
  hosts: all
  user: root
  environment:
    HOST: bull.simonknott.de
    LETSENCRYPT_EMAIL: simoknott@gmail.com
  tasks:
    - name: Deploy
      docker_service:
        project_name: Entschuldigungsverfahren
        definition:
          version: '2'
          services:
            mongodb:
              image: mongo:latest
              volumes:
                - "/data/db"
            api:
              build: ./api
              restart: always
              depends_on:
                - mongodb
              environment:
                - HOST
                - VIRTUAL_HOST=${HOST}
                - VIRTUAL_PATH=/api/
            ui:
              build: ./ui
              restart: always
              environment:
                - VIRTUAL_HOST=${HOST}
                - VIRTUAL_PATH=/
            nginx-proxy:
              image: joshtrow/nginx-proxy
              ports:
                - 80:80
                - 443:443
                - 8080:8080
              restart: always
              volumes:
                - "/var/run/docker.sock:/tmp/docker.sock:ro"


