---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui
        tier: backend
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
        - image: registry.gitlab.com/skn0tt/ente/ui:latest
          name: ui
          ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
    tier: backend
  ports:
  - protocol: TCP
    name: http
    port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
        - image: mongo
          name: mongodb
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
        - image: registry.gitlab.com/skn0tt/ente/api:latest
          name: api
          env:
            - name: "KUBERNETES"
              value: "true"
          ports:
          - containerPort: 80
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: LoadBalancer
  selector:
    app: api
    tier: backend
  ports:
  - protocol: TCP
    name: http
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      - path: /api
        backend:
          serviceName: api
          servicePort: 80
---
