- name: Update Compose
  hosts: all
  user: root
  environment:
    HOST: bull.simonknott.de
    LETSENCRYPT_EMAIL: simoknott@gmail.com
  tasks:
    - name: Deploy
      docker_service:
        project_name: Entschuldigungsverfahren
        pull: yes
        definition:
          version: '2'
          services:
            mongodb:
              image: mongo:latest
              volumes:
                - "/data/db"
            api:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:master
              restart: always
              depends_on:
                - mongodb
              environment:
                - HOST
                - VIRTUAL_HOST=${HOST}
                - VIRTUAL_PATH=/api/
                - NODE_ENV=production
                - LETSENCRYPT_HOST=${HOST}
                - LETSENCRYPT_EMAIL
            ui:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui:master
              restart: always
              environment:
                - VIRTUAL_HOST=${HOST}
                - VIRTUAL_PATH=/
                - LETSENCRYPT_HOST=${HOST}
                - LETSENCRYPT_EMAIL
            nginx-proxy:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/nginx-proxy:master
              ports:
                - 80:80
                - 443:443
                - 8080:8080
              restart: always
              volumes:
                - "/var/run/docker.sock:/tmp/docker.sock:ro"
                - "/etc/nginx/certs"
                - "/etc/nginx/vhost.d"
                - "/usr/share/nginx/html"
              labels:
                - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
            letsencrypt-nginx-proxy-companion:
              image: jrcs/letsencrypt-nginx-proxy-companion
              volumes_from:
                - nginx-proxy
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock:ro"
              
