---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  namespace: awesomeapps
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: entschuldigungsverfahren
spec:
  selector:
    matchLabels:
      app: entschuldigungsverfahren
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: entschuldigungsverfahren
    spec:
      containers:
        - image: mongo
          name: mongodb
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
        - image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/api:latest
          name: api
        - image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/web:latest
          name: web
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim  
      imagePullSecrets:
        - name: gitlab
    