- name: Update Compose
  hosts: all
  user: root
  tasks:
    - name: Deploy
      docker_service:
        project_name: Entschuldigungsverfahren
        definition:
          version: '2'
          services:
            mongodb:
              image: mongo:latest
              volumes:
                - /data/db
            api:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/api
              restart: always
              environment:
                NODE_ENV: "production"
              depends_on:
                - mongodb
            ui:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/ui
              restart: always
            reverseproxy:
              image: registry.gitlab.com/skn0tt/entschuldigungsverfahren/reverseproxy
              restart: always
              depends_on:
                - ui
                - api
              ports:
                - 80:80
                - 443:443
