version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
  web:
    build: ui/
    restart: on-failure
    ports:
      - "80:80"
  api:
    build: api/
    restart: on-failure
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"