version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - /data/db
    container_name: "mongodb"
  api:
    build: ./api
    restart: always
    depends_on:
      - mongodb
      - reverseproxy
  ui:
    build: ./ui
    restart: always
    depends_on:
      - reverseproxy
  reverseproxy:
    build: ./reverseproxy
    restart: always
    ports:
      - 80:80
      - 443:443