version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - /data/db
    container_name: "mongodb"
  api:
    build: api/
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
  web:
    build: ui/
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - api
    ports:
      - "80:80"
