version: '2'

services:

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ente
      - MYSQL_USER=ente
      - MYSQL_PASSWORD=root

  api:
    image: registry.gitlab.com/skn0tt/ente/api
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - railmail
      - rotator
    environment:
      - HOST
      - RAILMAIL_HOST=railmail
      - ROTATOR_HOST=rotator
      - SENTRY_DSN_API
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/api/

  railmail:
    image: skn0tt/railmail:v0.3.0
    restart: on-failure
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SENDER

  redis:
    image: redis

  rotator:
    image: skn0tt/secret-rotator:v0.2.0
    depends_on:
      - redis
    restart: on-failure
    environment:
      REDIS_HOSTNAME: redis
      ROTATION_PERIOD: 900

  ui:
    image: registry.gitlab.com/skn0tt/ente/ui
    restart: on-failure
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/
      - SENTRY_DSN_UI
      - CONFIG_VARS=SENTRY_DSN_UI

  nginx-proxy:
    image: registry.gitlab.com/skn0tt/ente/nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    depends_on:
      - api
      - ui
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
