version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - /data/db
    container_name: "mongodb"
  api:
    build: ./api
    restart: always
    depends_on:
      - mongodb
  ui:
    build: ./ui
    restart: always
  reverseproxy:
    build: ./reverseproxy
    restart: always
    depends_on:
      - ui
      - api
    ports:
      - 80:80
      - 443:443