version: '3'

services:
  # UI Service
  ui:
    environment:
      - LETSENCRYPT_HOST: "api.${HOST}"
      - LETSENCRYPT_EMAIL
  
  # API Service
  api:
    environment:
      NODE_ENV: "production"

  # Proxy
  nginx-proxy:
    environment:
      - LETSENCRYPT_HOST: "${HOST}"
      - LETSENCRYPT_EMAIL
  
  # LE Companion
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
