version: '2'

services:
  mongodb:
    ports:
      - 3500:27017
  api:
    ports:
      - 5555:5555
    command: "nodemon --inspect=0.0.0.0:5555 --watch dist"
    environment:
      - VIRTUAL_PORT=3000
    volumes:
      - ./api/dist:/usr/src/app/dist
