version: '2'

services:
  mongodb:
    ports:
      - 3500:27017
  api:
    ports:
      - 5555:5555
    environment:
      - VIRTUAL_PORT=3000
      - JWT_SECRET=secret
    volumes:
      - ./packages/api/src:/usr/src/app/packages/api/src
