version: '2'

services:
  mongodb:
    ports:
      - 3500:27017
    
  api:
    ports:
      - 5555:5555
    command: nodemon --watch 'packages/**/src/**/*.ts' --exec 'ts-node' packages/api/src/index.ts
    volumes:
      - ./packages/api/src:/usr/src/app/packages/api/src
      - ./packages/validator/src:/usr/src/app/packages/validator/src
      - ./packages/types/src:/usr/src/app/packages/types/src
      - ./packages/mail/src:/usr/src/app/packages/mail/src
