version: '3'

services:
  reverseproxy:
    build: reverseproxy/
    restart: always
    ports:
      - "80:80"
      - "443:443"
  mongodb:
    image: mongo:latest
    volumes:
      - /data/db
    container_name: "mongodb"
  api:
    build: api/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongodb
      - reverseproxy
  ui:
    build: ui/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - reverseproxy
