version: "3.7"
services:
  ente:
    build: .
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USERNAME: ente
      MYSQL_PASSWORD: root
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      REDIS_HOST: redis
      BASE_URL: "http://localhost:3000"
    ports:
      - 3000:3000
