version: '2'

services:

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ente
      - MYSQL_USER=ente
      - MYSQL_PASSWORD=root
    
  api:
    image: registry.gitlab.com/skn0tt/ente/api
    restart: always
    depends_on:
      - mysql
      - redis
      - rotator
    environment:
      - HOST
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/api/
  
  redis:
    image: redis

  rotator:
    image: registry.gitlab.com/skn0tt/ente/rotator
    depends_on:
      - redis
  ui:
    image: registry.gitlab.com/skn0tt/ente/ui
    restart: always
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/
  nginx-proxy:
    build: ./packages/nginx-proxy
    image: registry.gitlab.com/skn0tt/ente/nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    depends_on:
      - api
      - ui
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
