version: '2'

services:
  mongodb:
    ports:
      - 3500:27017
  api:
    ports:
      - 5555:5555
    command: "nodemon ./packages/api/ --inspect=0.0.0.0:5555 --watch ./packages/api/dist"
    environment:
      - VIRTUAL_PORT=3000
      - JWT_SECRET=secret
    volumes:
      - ./packages/api/dist:/usr/src/app/packages/api/dist
