version: '2'

services:
  
  mysql:
    ports:
      - 3306:3306

  ui:
    volumes:
      - ./packages/ente-ui/dist/:/app/
    
  api:
    ports:
      - 5555:5555
    command: nodemon --watch 'packages/**/src/**/*.ts' --exec 'ts-node' packages/ente-api/src/index.ts
    volumes:
      - ./packages/ente-api/src:/usr/src/app/packages/ente-api/src
      - ./packages/ente-validator/src:/usr/src/app/packages/ente-validator/src
      - ./packages/ente-types/src:/usr/src/app/packages/ente-types/src
      - ./packages/ente-mail/src:/usr/src/app/packages/ente-mail/src
      - ./packages/ente-db/src:/usr/src/app/packages/ente-db/src
