site_name: EntE
repo_url: https://gitlab.com/skn0tt/EntE/
repo_name: Gitlab
use_directory_urls: false
theme:
  name: 'material'
  custom_dir: docs/theme_customizations/
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js