site_name: EntE
site_url_de: https://skn0tt.gitlab.io/EntE/docs/de/
site_url_en: https://skn0tt.gitlab.io/EntE/docs/
site_url: https://skn0tt.gitlab.io/EntE/docs/de/
repo_url: https://gitlab.com/skn0tt/EntE/
repo_name: Gitlab
use_directory_urls: false
docs_dir: content
site_dir: site
theme:
  name: "material"
  custom_dir: ../theme_customizations/
  language: "de"
  palette:
    primary: "blue"
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
