@startuml Use
skinparam componentStyle uml2

frame "DigEnt" {
  folder "Entry" {
    ["Slot 1"] as S1
    ["Slot 2"] as S2
    ["Slot 3"] as S3
  }
}


Schüler --> Entry : "erstellt"
Eltern --> Entry : "genehmigt"
Stufenleiter --> Entry : "genehmigt"

S1 --> Lehrer : "informiert"
S2 --> Lehrer : "informiert"
S3 --> Lehrer : "informiert"

@enduml