version: '3.6'

services:

  ui:
    image: registry.gitlab.com/skn0tt/ente/ui:${UI_TAG}
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /"
    environment:
      SENTRY_DSN_UI: ${sentry.ui}
      ROTATION_PERIOD: ${config.rotation_period.ui}
      ALLOW_INSECURE: ${debug.allow_http}
      LANG: ${config.language}
      INSTANCE_INFO_DE: ${config.instanceInfo.de}
      INSTANCE_INFO_EN: ${config.instanceInfo.en}
      CONFIG_VARS: SENTRY_DSN_UI,ROTATION_PERIOD,ALLOW_INSECURE,LANG,INSTANCE_INFO_DE,INSTANCE_INFO_EN
    networks:
      - ente_bridge

  api:
    image: registry.gitlab.com/skn0tt/ente/api:${API_TAG}
    restart: on-failure
    depends_on:
      - redis
      - signer
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /api/"
    environment:
      VERSION: ${API_TAG}
      NODE_ENV: ${debug.environment}
      BASE_URL: ${config.baseUrl}
      SIGNER_BASEURL: http://signer:3000
      ENABLE_CRON_JOBS: "true"
      CRON_WEEKLY_SUMMARY: "0 16 * * 5"
      SENTRY_DSN: ${sentry.api}
      MYSQL_HOST: ${mysql.host}
      MYSQL_PORT: ${mysql.port}
      MYSQL_DATABASE: ${mysql.database}
      MYSQL_USERNAME: ${mysql.username}
      MYSQL_PASSWORD: ${mysql.password}
      SMTP_HOST: ${smtp.host}
      SMTP_PORT: ${smtp.port}
      SMTP_USERNAME: ${smtp.username}
      SMTP_PASSWORD: ${smtp.password}
      SMTP_SENDER: ${smtp.sender}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - ente_bridge

  signer:
    image: skn0tt/signer:v0.5.0
    depends_on:
      - redis
    restart: on-failure
    environment:
      REDIS_HOSTNAME: redis
      TOKEN_EXPIRY: ${config.rotation_period.keys}
      ROTATION_INTERVAL: ${config.rotation_period.keys}
      ROTATE_ON_STARTUP: "true"
      ASYMMETRIC_SIGNING: "true"
    networks:
      - ente_bridge

  redis:
    image: redis:4.0.10
    networks:
      - ente_bridge

  traefik:
    image: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.exposedbydefault=false"
    depends_on:
      - api
      - ui
    ports:
      - "${config.port}:80"
      - "${debug.traefik_dashboard_port}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ente_bridge

networks:
  ente_bridge:
    driver: bridge
    driver_opts:
        com.docker.network.bridge.name: ente_bridge
