version: '3.6'

services:
  api:
    image: registry.gitlab.com/skn0tt/ente/api:${API_VERSION}
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - railmail
      - rotator
    environment:
      - NODE_ENV="production"
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL
      - HOST
      - RAILMAIL_HOST=railmail
      - ROTATOR_HOST=rotator
      - SENTRY_DSN_API
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ente
      - MYSQL_USERNAME=ente
      - MYSQL_PASSWORD=root
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/api/

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ente
      - MYSQL_USER=ente
      - MYSQL_PASSWORD=root

  railmail:
    image: skn0tt/railmail:v0.3.0
    restart: on-failure
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SENDER

  rotator:
    image: skn0tt/secret-rotator:v0.2.0
    depends_on:
      - redis
    restart: on-failure
    environment:
      REDIS_HOSTNAME: redis
      ROTATION_PERIOD: 900

  redis:
    image: redis:4.0.10

  ui:
    image: registry.gitlab.com/skn0tt/ente/ui:${UI_VERSION}
    restart: on-failure
    environment:
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/
      - SENTRY_DSN_UI
      - CONFIG_VARS=SENTRY_DSN_UI

  nginx-proxy:
    image: registry.gitlab.com/skn0tt/ente/nginx-proxy:${NGINX_PROXY_VERSION}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    depends_on:
      - api
      - ui
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "le_certs:/etc/nginx/certs"
      - "le_vhost:/etc/nginx/vhost.d"
      - "le_html:/usr/share/nginx/html"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "le_certs:/etc/nginx/certs:ro"
      - "le_vhost:/etc/nginx/vhost.d"
      - "le_html:/usr/share/nginx/html"

volumes:
  le_certs:
  le_vhost:
  le_html:
