version: '3.6'

services:

  ui:
    image: registry.gitlab.com/skn0tt/ente/ui:${UI_VERSION}
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /"
    environment:
      - SENTRY_DSN_UI
      - CONFIG_VARS=SENTRY_DSN_UI

  api:
    image: registry.gitlab.com/skn0tt/ente/api:${API_VERSION}
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - railmail
      - signer
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip: /api/"
    environment:
      - NODE_ENV="production"
      - HOST
      - RAILMAIL_HOST=railmail
      - SIGNER_HOST=signer:3000
      - SENTRY_DSN_API
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ente
      - MYSQL_USERNAME=ente
      - MYSQL_PASSWORD=root

  mysql:
    image: mariadb:10.3.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ente
      - MYSQL_USER=ente
      - MYSQL_PASSWORD=root

  railmail:
    image: skn0tt/railmail:v0.3.0
    restart: on-failure
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SENDER

  signer:
    image: skn0tt/signer:v0.4.0
    depends_on:
      - redis
    restart: on-failure
    environment:
      - REDIS_HOSTNAME=redis
      - TOKEN_EXPIRY=900
      - ROTATION_INTERVAL=900
      - ASYMMETRIC_SIGNING=true

  redis:
    image: redis:4.0.10

  traefik:
    image: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.exposedbydefault=false"
    depends_on:
      - api
      - ui
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
