COMPOSE_PROJECT_NAME: ente

config:
  # host:
  port: 80
  rotation_period:
    keys: 900
    ui: 300

sentry: # Override when using Sentry
  api: undefined
  ui: undefined

# mysql:
  # host:
  # port:
  # username:
  # password:
  # database:

# smtp:
  # host:
  # port:
  # username:
  # password:
  # sender:

debug:
  traefik_dashboard_port: 8080
  allow_http: false
  environment: "production"

UI_TAG: v0.6.0
API_TAG: v0.6.0
