COMPOSE_PROJECT_NAME: ente
HOST: localhost
SMTP_HOST: smtp.ethereal.email
SMTP_PASSWORD: mWgCFb9JcJxdeKa6RE
SMTP_PORT: "587"
SMTP_SENDER: EntE@simonknott.de
SMTP_USERNAME: louf4yh5lnkyg2h3@ethereal.email
API_VERSION: v0.3.1
UI_VERSION: v0.3.1
NGINX_PROXY_VERSION: v0.3.1
PORT_HTTP: 80
PORT_HTTPS: 443
PORT_TRAEFIK_DASHBOARD: 8080
