COMPOSE_PROJECT_NAME: ente
HOST: localhost
SMTP_HOST: smtp.ethereal.email
SMTP_PASSWORD: mWgCFb9JcJxdeKa6RE
SMTP_PORT: "587"
SMTP_SENDER: EntE@simonknott.de
SMTP_USERNAME: louf4yh5lnkyg2h3@ethereal.email
API_VERSION: master
UI_VERSION: master
NGINX_PROXY_VERSION: master
