config:
  # baseUrl:
  port: 80
  rotation_period:
    keys: 900
    ui: 300

sentry: # Override when using Sentry
  api: ~
  ui: ~

# mysql:
#   host:
#   port:
#   username:
#   password:
#   database:
#   timezone:

# smtp:
#   host:
#   port:
#   username:
#   password:
#   sender:
#   address:

smtp:
  retryDelay: 3600000

debug:
  traefik_dashboard_port: 8080
  allow_http: false
  environment: "production"

UI_TAG: v0.26.0
API_TAG: v0.26.0
