export type errorPayload = Error;

export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_ERROR = 'CREATE_ENTRY_ERROR';

export const GET_ENTRY_REQUEST = 'GET_ENTRY_REQUEST';
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';
export const GET_ENTRY_ERROR = 'GET_ENTRY_ERROR';

export const GET_ENTRIES_REQUEST = 'GET_ENTRIES_REQUEST';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
export const GET_ENTRIES_ERROR = 'GET_ENTRIES_ERROR';