export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_ERROR = 'CREATE_ENTRY_ERROR';

export const CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_ERROR = 'CREATE_USERS_ERROR';

export const SIGN_ENTRY_REQUEST = 'SIGN_ENTRY_REQUEST';
export const SIGN_ENTRY_SUCCESS = 'SIGN_ENTRY_SUCCESS';
export const SIGN_ENTRY_ERROR = 'SIGN_ENTRY_ERROR';

export const UNSIGN_ENTRY_REQUEST = 'UNSIGN_ENTRY_REQUEST';
export const UNSIGN_ENTRY_SUCCESS = 'UNSIGN_ENTRY_SUCCESS';
export const UNSIGN_ENTRY_ERROR = 'UNSIGN_ENTRY_ERROR';

export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_ENTRY_REQUEST = 'GET_ENTRY_REQUEST';
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';
export const GET_ENTRY_ERROR = 'GET_ENTRY_ERROR';

export const GET_ENTRIES_REQUEST = 'GET_ENTRIES_REQUEST';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
export const GET_ENTRIES_ERROR = 'GET_ENTRIES_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_CHILDREN_REQUEST = 'GET_CHILDREN_REQUEST';
export const GET_CHILDREN_SUCCESS = 'GET_CHILDREN_SUCCESS';
export const GET_CHILDREN_ERROR = 'GET_CHILDREN_ERROR';

export const GET_NEEDED_USERS_REQUEST = 'GET_NEEDED_USERS_REQUEST';
export const GET_NEEDED_USERS_SUCCESS = 'GET_NEEDED_USERS_SUCCESS';
export const GET_NEEDED_USERS_ERROR = 'GET_NEEDED_USERS_ERROR';

export const GET_TEACHERS_REQUEST = 'GET_TEACHERS_REQUEST';
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS';
export const GET_TEACHERS_ERROR = 'GET_TEACHERS_ERROR';

export const GET_SLOTS_REQUEST = 'GET_SLOTS_REQUEST';
export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';
export const GET_SLOTS_ERROR = 'GET_SLOTS_ERROR';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const ADD_RESPONSE = 'ADD_RESPONSE';

export const LOGOUT = 'LOGOUT';
