version: '3.6'

services:

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ente
      MYSQL_PASSWORD: root
      MYSQL_USER: ente

  ui:
    volumes:
      - ${PWD}/packages/ente-ui/dist/:/app/
    
  api:
    ports:
      - 5555:5555
    command: nodemon --watch 'packages/**/src/**/*.ts' --exec 'ts-node' packages/ente-api/src/main.ts
    volumes:
      - ${PWD}/packages/ente-api/src:/usr/src/app/packages/ente-api/src
      - ${PWD}/packages/ente-types/src:/usr/src/app/packages/ente-types/src
