mysql:
  host: host.docker.internal
  port: 3306
  database: ente
  username: ente
  password: root
  timezone: Z

smtp:
  host: mailhog
  password: "ignoredbymailhog"
  port: "1025"
  sender: Example-EntE
  address: EntE@simonknott.de
  username: "ignoredbymailhog"

config:
  baseUrl: http://localhost

debug:
  allow_http: true
  environment: "debug"

API_TAG: latest
UI_TAG: latest
