mysql:
  host: host.docker.internal
  port: 3306
  database: ente
  username: ente
  password: root
  timezone: Z

smtp:
  host: mailhog
  password: "ignoredbymailhog"
  port: "1025"
  sender: Example-EntE
  address: EntE@simonknott.de
  username: "ignoredbymailhog"

config:
  instanceInfo:
    de: "Hallo%20Welt,%20dies%20ist%20ein%20Test-Server."
    en: "Hello%20world,%20this%20is%20a%20test-server."
  language: de
  baseUrl: http://localhost

debug:
  allow_http: true
  environment: "debug"

API_TAG: latest
UI_TAG: latest
