version: '3.6'

services:

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ente
      MYSQL_PASSWORD: root
      MYSQL_USER: ente
