version: "3.6"

services:
  ui:
    volumes:
      - ${PWD}/packages/ente-ui/dist/:/app/

  api:
    ports:
      - 5555:5555
    volumes:
      - ${PWD}/packages/ente-api/src:/usr/src/app/packages/ente-api/src
      - ${PWD}/packages/ente-types/src:/usr/src/app/packages/ente-types/src
