version: "3.6"

services:
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ente
      MYSQL_PASSWORD: root
      MYSQL_USER: ente

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025
    networks:
      - ente_bridge
