FROM node AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

COPY . ./
RUN yarn build

RUN yarn global add pkg

RUN /usr/local/bin/pkg --targets node8-alpine-x64 --output index dist/index.js

FROM alpine:latest
COPY --from=build /app/index ./index

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl", "-f", "http://localhost/status" ]

EXPOSE 80
CMD [ "/index" ]